In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [3]:
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [4]:
def select_pca(indep_X, n_components):
    pca = PCA(n_components=n_components)
    pca_features = pca.fit_transform(indep_X)
    explained_variance = pca.explained_variance_ratio_
    return pca_features,explained_variance
    
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    # Use transform, not fit_transform, on the test set
        return X_train, X_test, y_train, y_test
    
 
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report 
        #from sklearn.metrics import confusion_matrix
        #cm = confusion_matrix(y_test, y_pred)
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return  classifier,Accuracy,report,X_test,y_test,cm

def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      
    
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
   
def Navie(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm         
    
    
def knn(X_train,y_train,X_test):
           
        # Fitting K-NN to the Training set
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      


def random(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def selectk_Classification(pcalist,acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['pcalist'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
        dataframe.index.name = 'PCA Components'
    return dataframe

In [5]:
dataset = pd.read_csv('prep.csv',index_col=None)
X = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, 13].values

In [6]:
df2=dataset

In [7]:
print(df2.columns)

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [8]:
df2 = pd.get_dummies(df2, dtype=int,drop_first='True')

In [9]:
df2

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [10]:
df2["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [11]:
indep_X=df2.drop(columns=['classification_yes'])
dep_Y=df2['classification_yes']

In [12]:
df2

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [24]:
pca_features = select_pca(indep_X,2)  # You only need indep_X and the number of components
       
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [25]:
pca_features

(array([[-3.30658089e-02, -2.57903995e+00],
        [ 3.89172279e+03, -2.21107937e+01],
        [-2.33353473e-01, -5.58806163e+01],
        [-6.39038425e-02, -8.54408308e+00],
        [ 3.99172054e+03, -2.28392970e+01],
        [ 8.29153515e+03, -8.53656232e+01],
        [-2.40823821e+03,  3.98946764e-02],
        [-1.70848800e+03, -7.01393145e+01],
        [-4.19087893e-02, -4.73506451e+00],
        [-2.66648721e-01, -6.82837890e+01],
        [ 1.91744268e+02, -8.93753936e+00],
        [ 1.89176138e+03, -1.05745096e+01],
        [-1.80840918e+03, -4.77060707e+01],
        [ 1.09189823e+03,  3.09113697e+01],
        [-7.08466354e+02, -6.71107662e+01],
        [-2.20843743e+03, -5.43079236e+01],
        [-1.40843674e+03, -5.67055444e+01],
        [ 2.79126492e+03, -1.45242843e+02],
        [-1.20834433e+03, -3.29470784e+01],
        [-1.50820299e+03,  3.72123380e+00],
        [-2.00341082e-01, -4.75270904e+01],
        [-3.90818812e+03,  1.23191896e+01],
        [-2.90829687e+03, -1.79335892e+01],
        [-2.15213602e-02, -1.80116196e+00],
        [ 3.99160981e+03, -5.83158364e+01],
        [-5.08427421e+02, -5.65454144e+01],
        [ 1.39147362e+03, -8.75729315e+01],
        [-1.20835493e+03, -3.72425365e+01],
        [-4.10837102e+03, -3.66343049e+01],
        [-2.10842348e+03, -5.21222472e+01],
        [-1.50728125e+03,  2.58398223e+02],
        [-2.60825483e+03, -5.44349205e+00],
        [-2.80827495e+03, -1.38081761e+01],
        [ 2.29156697e+03, -6.61277523e+01],
        [-1.50833198e+03, -2.85333744e+01],
        [ 7.91652504e+02, -3.81529289e+01],
        [-1.40843388e+03, -5.82184898e+01],
        [-1.50787043e+03,  9.85790902e+01],
        [-2.89237300e-01, -7.46471656e+01],
        [ 1.91702581e+02, -2.36337007e+01],
        [-1.90845798e+03, -6.45534971e+01],
        [-1.08589289e-01, -2.47116938e+01],
        [ 1.49154106e+03, -7.22555293e+01],
        [-3.00850752e+03, -7.35735769e+01],
        [-1.45799155e-01, -4.05464944e+01],
        [ 9.91706740e+02, -2.49359495e+01],
        [ 5.91575021e+02, -5.97081991e+01],
        [ 1.79154837e+03, -6.88184960e+01],
        [-8.75711904e-02, -1.78405287e+01],
        [ 2.29165002e+03, -4.23047395e+01],
        [ 9.91533516e+02, -7.26567256e+01],
        [-5.80801232e+03,  4.70456495e+01],
        [-1.70839158e+03, -4.67980030e+01],
        [-1.60839492e+03, -4.73332834e+01],
        [-1.40842139e+03, -5.61839435e+01],
        [-1.70838877e+03, -4.55835824e+01],
        [-2.20827899e+03, -1.55286068e+01],
        [-6.08478093e+02, -7.17226274e+01],
        [-4.10826295e+03, -7.04253106e+00],
        [ 1.89153859e+03, -7.21239027e+01],
        [-2.34273595e-02, -1.43144356e+00],
        [ 1.18352301e-01,  2.30343519e+01],
        [-6.20822473e+03,  7.21766740e+00],
        [-1.49758628e-01, -3.64842822e+01],
        [-1.74355081e-01, -4.51079755e+01],
        [ 7.91661846e+02, -3.56206149e+01],
        [ 1.91575493e+02, -5.99930748e+01],
        [ 2.09175787e+03, -1.30423187e+01],
        [-1.00843758e+03, -6.10093495e+01],
        [-5.08320347e+02, -4.50091806e+01],
        [-3.48470721e-03, -3.57779187e-01],
        [-4.10835645e+03, -3.30694861e+01],
        [-3.40838243e+03, -4.09628617e+01],
        [ 9.91526763e+02, -7.39066881e+01],
        [-2.60835860e+03, -3.70413466e+01],
        [ 3.91635610e+02, -4.65599818e+01],
        [-2.60844619e+03, -5.96878684e+01],
        [-4.30820104e+03,  1.01193513e+01],
        [-2.90834113e+03, -3.07320634e+01],
        [-1.40834799e+03, -3.65754973e+01],
        [-1.52778627e-01, -4.16101730e+01],
        [ 6.91565210e+02, -6.35143423e+01],
        [-1.10840242e+03, -5.10246055e+01],
        [-1.32768965e-01, -3.28034718e+01],
        [-1.27300973e-01, -3.00377905e+01],
        [ 9.91719836e+02, -2.34317213e+01],
        [-2.60843002e+03, -5.64519685e+01],
        [-4.60833010e+03, -3.84850763e+01],
        [ 3.92254298e+02,  1.15373884e+02],
        [ 1.99171373e+03, -2.32123166e+01],
        [-1.46031826e-01, -3.57922181e+01],
        [ 4.27918079e-03,  1.14098172e+00],
        [ 3.02645684e-01,  7.66975205e+01],
        [-2.10828479e+03, -1.87737508e+01],
        [ 6.91675040e+02, -3.37258421e+01],
        [-1.20833512e+03, -3.35277838e+01],
        [-1.08199078e+02, -2.66837004e-01],
        [ 1.39167680e+03, -4.53798686e+01],
        [-8.41062777e+00, -5.55902617e+01],
        [-3.40826424e+03, -8.99801967e+00],
        [-1.30841081e+03, -5.42736909e+01],
        [-6.08487888e+02, -7.50978125e+01],
        [ 6.49173280e+03, -2.86842835e+01],
        [-1.50844184e+03, -6.28895017e+01],
        [-6.08283467e+02, -2.03813295e+01],
        [-1.50392790e-01, -3.78129775e+01],
        [-1.20836422e+03, -4.11765245e+01],
        [-1.00832290e+03, -3.03395465e+01],
        [-3.91874121e-02, -5.85419870e+00],
        [ 1.19160987e+03, -5.20762523e+01],
        [-1.20839876e+03, -5.17749297e+01],
        [-6.08198456e+02,  1.35058796e+00],
        [-9.08414517e+02, -5.56883150e+01],
        [-7.08400714e+02, -5.27793620e+01],
        [-3.55902255e-02, -6.09923293e+00],
        [ 9.91717080e-01,  2.72839836e+02],
        [-2.90741465e+03,  2.18611964e+02],
        [ 1.79161123e+03, -5.37578346e+01],
        [ 7.92256762e+02,  1.19094636e+02],
        [ 1.06916159e+04, -7.15171157e+01],
        [-2.70826592e+03, -1.93730783e+01],
        [ 6.91550802e+02, -6.97898212e+01],
        [ 1.91678066e+02, -3.35822033e+01],
        [ 7.91645519e+02, -4.23634881e+01],
        [ 6.91648156e+02, -4.73263828e+01],
        [ 5.30512674e-02,  9.88720419e+00],
        [ 6.19184660e+03, -3.77930012e+00],
        [ 2.40436020e-01,  6.55066945e+01],
        [-3.08155751e+02,  1.04703229e+01],
        [-9.76997178e-02, -2.32694988e+01],
        [-2.10828879e+03, -1.97723202e+01],
        [ 2.59159054e+03, -6.07362533e+01],
        [-2.70836070e+03, -3.97220126e+01],
        [-1.89638447e-01, -5.05836231e+01],
        [-1.01304069e-01, -2.94339682e+01],
        [ 7.91985306e+02,  4.86134733e+01],
        [-2.80820022e+03,  5.79235786e+00],
        [ 1.79170582e+03, -3.15916084e+01],
        [-2.11631357e-01, -5.59143635e+01],
        [-3.08417197e+02, -5.75648509e+01],
        [-1.40828286e+03, -2.08379299e+01],
        [-5.08268345e+02, -1.62879186e+01],
        [-1.08364377e+02, -4.39198186e+01],
        [-3.20831753e+03, -2.49580550e+01],
        [-1.70829082e+03, -2.40419259e+01],
        [-1.50828304e+03, -3.09221001e+01],
        [-2.00829241e+03, -2.16864930e+01],
        [-2.20816340e+03,  5.59525123e+00],
        [-1.10167678e-01, -2.68193363e+01],
        [ 2.07961023e-01,  5.98866648e+01],
        [-1.20831371e+03, -3.54681662e+01],
        [-3.40818051e+03, -3.73757369e+00],
        [ 1.09167997e+03, -3.40534580e+01],
        [ 9.91652843e+02, -4.23144998e+01],
        [-2.40847520e+03, -6.89094446e+01],
        [ 1.19182382e+03, -6.87024993e+00],
        [-2.80828849e+03, -1.92572826e+01],
        [ 1.23111350e+00,  3.36659973e+02],
        [-1.63161643e-01, -4.26684828e+01],
        [-2.60828123e+03, -2.68673964e+01],
        [-1.90832645e+03, -4.08665560e+01],
        [ 7.89181266e+03, -2.59467357e+01],
        [ 4.79213296e+03,  7.01305207e+01],
        [-3.70826848e+03, -1.37018963e+01],
        [ 1.99207967e+03,  7.18785592e+01],
        [ 8.83653955e-04,  3.35386226e-01],
        [ 2.09158987e+03, -6.13938418e+01],
        [-3.70840379e+03, -4.79227352e+01],
        [ 1.09174725e+03, -1.69758535e+01],
        [-1.10835719e+03, -4.18408828e+01],
        [-2.25076847e-01, -5.93920707e+01],
        [-1.08391488e+02, -5.17553942e+01],
        [-3.08288089e+02, -2.31778817e+01],
        [ 1.09156764e+03, -6.40701967e+01],
        [ 1.19177365e+03, -1.30770870e+01],
        [-3.40779679e+03,  1.04887915e+02],
        [-3.70827840e+03, -1.43196215e+01],
        [-4.10826340e+03, -8.99831921e+00],
        [-2.10838615e+03, -4.56748693e+01],
        [ 3.69155029e+03, -8.20345037e+01],
        [ 2.59163632e+03, -5.77791027e+01],
        [-4.10817116e+03,  1.30892524e+01],
        [ 2.10079245e-01,  5.96754453e+01],
        [-7.08332318e+02, -3.45688374e+01],
        [ 2.36694624e-01,  6.17121514e+01],
        [ 2.43479103e-01,  6.42031363e+01],
        [ 6.59092398e-02,  1.60550119e+01],
        [ 3.00005262e-01,  8.25471506e+01],
        [-1.17420946e-01, -2.88074743e+01],
        [ 1.91748665e+02, -2.42322941e+01],
        [-2.60737056e+03,  2.22551023e+02],
        [-1.86366889e-01, -4.88729829e+01],
        [-2.13677559e-02, -3.49528569e+00],
        [-8.48135586e+00, -7.61982351e+01],
        [-4.41855848e-03, -1.77141279e+00],
        [ 1.04514663e-02,  4.06873105e-02],
        [ 5.19231206e+03,  1.27906256e+02],
        [-2.00857038e-01, -5.32380269e+01],
        [ 6.19237143e+03,  1.27733730e+02],
        [-1.00792807e+03,  7.15397518e+01],
        [-1.20832272e+03, -3.08747624e+01],
        [-1.60826525e+03, -1.46401429e+01],
        [ 6.91733794e+02, -2.16093874e+01],
        [-1.70835805e+03, -3.92884034e+01],
        [-2.08377738e+02, -4.74038286e+01],
        [-1.70821714e+03, -3.22565581e+00],
        [-2.00819408e+03, -2.85367694e+00],
        [ 3.39184584e+03,  3.93644627e+00],
        [ 9.46323703e-01,  2.60504720e+02],
        [ 4.09197049e+03,  4.07503072e+01],
        [ 1.99232850e+03,  1.39092023e+02],
        [ 4.11460555e-01,  1.04832059e+02],
        [-3.00784202e+03,  7.79951874e+01],
        [-2.80823685e+03, -4.54647335e+00],
        [ 2.59149480e+03, -8.87215301e+01],
        [-9.08277425e+02, -1.90680674e+01],
        [-4.20793199e+03,  5.63250239e+01],
        [-4.10811358e+03,  2.40399361e+01],
        [-1.20828505e+03, -2.41355982e+01],
        [-4.20810208e+03,  3.07810192e+01],
        [-2.20831090e+03, -2.61681795e+01],
        [ 1.99163055e+03, -5.19352468e+01],
        [ 2.59169959e+03, -3.20412804e+01],
        [-1.80824036e+03, -9.68314917e+00],
        [ 4.79214914e+03,  8.41850367e+01],
        [-3.08360012e+02, -4.57162422e+01],
        [-1.70835981e+03, -4.22178088e+01],
        [ 6.91548912e+02, -6.85994497e+01],
        [-1.60827695e+03, -1.68788857e+01],
        [ 4.02601428e-02,  6.89104380e+00],
        [-4.60829840e+03, -3.39756518e+01],
        [ 2.49233753e+03,  1.41140850e+02],
        [-2.40798644e+03,  6.11979661e+01],
        [ 1.79920525e+04,  3.43179911e+01],
        [ 1.39226379e+03,  1.13209462e+02],
        [ 7.29220408e+03,  8.46443784e+01],
        [ 1.79279126e+03,  2.65295062e+02],
        [-1.70825897e+03, -1.45316458e+01],
        [-1.90833807e+03, -3.33136393e+01],
        [-6.08471264e+02, -7.48696850e+01],
        [ 2.99218585e+03,  9.89466778e+01],
        [-2.20806839e+03,  3.12749256e+01],
        [-1.57748596e-02, -6.84961247e+00],
        [ 1.31917218e+04, -5.04480091e+01],
        [ 7.35546001e-02,  2.04676287e+01],
        [-4.90432337e-02, -1.22787866e+01],
        [ 2.09164653e+03, -4.98697842e+01],
        [ 6.79225814e+03,  1.10109977e+02],
        [ 6.21992016e-03,  5.62358404e-01],
        [-4.20775292e+03,  1.27265187e+02],
        [-1.06201342e-01, -3.26681083e+01],
        [ 3.59305283e+03,  3.30515184e+02],
        [-8.64177554e-02, -2.43567982e+01],
        [ 4.39435462e-01,  1.19238933e+02],
        [ 2.29169712e+03, -3.21904864e+01],
        [ 2.39179311e+03, -8.85715277e+00],
        [ 2.29172909e+03, -2.47502215e+01],
        [ 2.09151980e+03, -8.00763357e+01],
        [ 7.91982267e+02,  3.61703414e+01],
        [-8.31080257e+00, -3.66966556e+01],
        [ 1.19183592e+03,  4.75999111e+00],
        [-1.07456092e+02,  2.04111963e+02],
        [ 1.39180714e+03, -4.26096914e+00],
        [-7.99849476e-02, -2.13097124e+01],
        [-1.93807833e-01, -5.16485259e+01],
        [-1.40830817e+03, -2.68947349e+01],
        [ 7.91733615e+02, -2.08504369e+01],
        [-9.07186923e+02,  2.74779197e+02],
        [-3.10835253e+03, -3.94269023e+01],
        [ 9.21400608e+01,  9.18813385e+01],
        [-2.11814096e-01, -5.70631806e+01],
        [-5.08287514e+02, -2.57610832e+01],
        [ 1.79180106e+03, -6.23625196e+00],
        [ 4.39241116e+03,  1.51504240e+02],
        [ 2.59186183e+03,  1.02163883e+01],
        [-3.70823735e+03, -5.36573666e+00],
        [-3.00843121e+03, -5.95809838e+01],
        [-3.90731579e+03,  2.44428615e+02],
        [ 1.39180657e+03, -4.45678849e+00],
        [ 1.39226559e+03,  1.22741445e+02],
        [ 2.99167861e+03, -4.05289692e+01],
        [ 2.09155748e+03, -7.50921193e+01],
        [-1.10825922e+03, -1.67549901e+01],
        [-4.08342174e+02, -3.82021572e+01],
        [-6.93151910e-03, -2.19829121e+00],
        [-9.07844503e+02,  9.36593418e+01],
        [-7.80420330e-02, -2.80989973e+01],
        [-1.74220451e-01, -4.63373796e+01],
        [-9.08113181e+02,  1.94295932e+01],
        [ 1.39294615e+03,  3.07436145e+02],
        [-3.08360673e+02, -4.51843018e+01],
        [-2.00838362e+03, -4.75201813e+01],
        [ 1.39223506e+03,  1.13519887e+02],
        [-1.07644391e-01, -3.27350434e+01],
        [ 3.49160237e+03, -6.55015100e+01],
        [ 6.91604624e+02, -5.92834815e+01],
        [-1.60831183e+03, -2.96836321e+01],
        [ 5.92354203e+02,  1.45008287e+02],
        [-2.90832702e+03, -3.86903311e+01],
        [-4.31227572e-02, -1.24540247e+01],
        [-1.70762240e+03,  1.59265662e+02],
        [ 3.09766538e-01,  7.78412769e+01],
        [ 2.29159246e+03, -6.56604049e+01],
        [ 1.22326201e-01,  2.85748065e+01],
        [ 1.09193295e+03,  3.36148926e+01],
        [-2.41373899e-01, -7.05038700e+01],
        [-3.40796828e+03,  6.57334127e+01],
        [ 1.19164599e+03, -4.60401592e+01],
        [ 1.19154823e+03, -7.20123488e+01],
        [ 4.42574716e-02,  8.72823295e+00],
        [ 1.19287414e+03,  2.88825304e+02],
        [ 3.45741436e-01,  9.49924964e+01],
        [-3.10838741e+03, -4.69919637e+01],
        [ 2.59161568e+03, -5.59669483e+01],
        [-6.51078886e-03, -4.53530430e+00],
        [ 3.99409018e-01,  8.33816626e+01],
        [ 1.42935085e-02,  2.25092757e+00],
        [-1.30834252e+03, -4.12017726e+01],
        [-1.90811592e+03,  1.56395789e+01],
        [-1.50749373e+03,  1.93651905e+02],
        [-2.50835681e+03, -4.10164928e+01],
        [-1.64960013e-01, -4.62078877e+01],
        [ 3.79202591e+03,  4.81356377e+01],
        [-1.46531528e-01, -4.44539638e+01],
        [ 2.59187484e+03,  5.93325892e+00],
        [-1.31255688e-02, -3.67798041e+00],
        [-3.50809681e+03,  3.23827985e+01],
        [-4.07845518e+02,  9.17547339e+01],
        [-1.70827388e+03, -1.89960865e+01],
        [ 1.19225312e+03,  1.15196639e+02],
        [ 4.89417075e-02,  7.88790732e+00],
        [ 3.84793096e-01,  1.04440063e+02],
        [ 6.56791216e-02,  1.88186560e+01],
        [ 3.09207259e+03,  6.07369363e+01],
        [ 8.91559483e+02, -6.95782142e+01],
        [ 1.70916469e-01,  3.74461965e+01],
        [ 7.63946111e-02,  1.51091553e+01],
        [ 2.86713981e-03, -9.06597774e-01],
        [-2.60808554e+03,  3.07020702e+01],
        [-2.08134488e+02,  8.16688814e+00],
        [-8.22785875e+00, -1.78891485e+01],
        [ 1.77936845e-01,  4.29188603e+01],
        [-3.90827100e+03, -1.55511843e+01],
        [ 1.29152690e+03, -7.97525728e+01],
        [-2.80787992e+03,  8.51510414e+01],
        [ 2.29161315e+03, -6.28701562e+01],
        [ 6.79171960e+03, -4.43119021e+01],
        [ 1.00018934e+00,  2.71607542e+02],
        [ 7.92353401e+02,  1.47241364e+02],
        [ 1.39153447e+03, -7.67747973e+01],
        [-7.08177637e+02,  2.92491176e+00],
        [-2.60841843e+03, -5.93948744e+01],
        [-1.50819282e+03, -2.73873427e+00],
        [ 6.30406613e-01,  1.71410567e+02],
        [ 5.72947795e-01,  1.56139623e+02],
        [-1.44473469e-01, -4.87397017e+01],
        [-7.44434688e-02, -2.29548690e+01],
        [ 3.61732683e-01,  8.17508647e+01],
        [ 2.09163115e+03, -5.12242708e+01],
        [-6.08331898e+02, -4.01176641e+01],
        [ 1.04914513e+04, -1.18337431e+02],
        [-1.20771834e+03,  1.21867516e+02],
        [-1.40760242e+03,  1.57075664e+02],
        [-1.81500468e-01, -5.23391079e+01],
        [ 3.31049118e-01,  8.64265677e+01],
        [ 2.59171081e+03, -3.20483358e+01],
        [ 8.91694194e+02, -3.40301031e+01],
        [ 9.91796886e+02, -1.19475344e+01],
        [-1.22974530e-01, -3.73564867e+01],
        [-2.40839198e+03, -5.15186926e+01],
        [ 1.89183236e+03,  2.93208218e-01],
        [-9.65383185e-02, -2.76346665e+01],
        [ 4.38002370e-02,  9.58443490e+00],
        [-1.08321124e+02, -3.75999058e+01],
        [ 1.89165042e+03, -4.83952804e+01],
        [-2.04740153e-01, -5.81184483e+01],
        [ 2.89189553e+03,  6.60627607e+00],
        [-1.01349976e-01, -3.81057058e+01],
        [ 4.29220431e+03,  8.56283572e+01],
        [ 1.00648549e-01,  2.37872142e+01],
        [-8.45267553e-02, -2.97350915e+01],
        [-4.08314720e+02, -3.58379054e+01],
        [ 1.16106624e-02,  2.94328814e-02],
        [ 1.19178895e+03, -1.08471348e+01],
        [-2.10816372e+03,  8.85769648e+00],
        [-3.30826779e+03, -1.69454088e+01],
        [ 9.91806811e+02, -5.57854231e+00],
        [ 1.39180032e+03, -9.61612778e+00],
        [ 4.39164163e+03, -5.90169769e+01],
        [-5.08165664e+02, -1.00775041e-02],
        [-1.20670760e-01, -4.00033432e+01],
        [-2.10818539e+03, -1.89795614e+00],
        [-1.72922431e-02, -3.76878100e+00],
        [-1.92625218e-01, -4.98327259e+01],
        [ 1.39203651e+03,  6.13511219e+01],
        [ 2.73721803e-01,  7.26879909e+01],
        [ 7.91720192e+02, -3.16721166e+01],
        [ 2.32304509e-01,  6.17888936e+01],
        [ 9.16198005e+01, -4.95271746e+01]]),
 array([9.98650909e-01, 8.79001590e-04]))

In [26]:
print(type(pca_features))
print(len(pca_features))

<class 'tuple'>
2

In [27]:
X_train, X_test, y_train, y_test = split_scalar(pca_features, dep_Y)
pcalist = [1,2,3,4]
for n in pcalist:
    pca_features = select_pca(indep_X, n)
       
    classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
    acclog.append(Accuracy)
    
    classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
    accsvml.append(Accuracy)
        
    classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
    accsvmnl.append(Accuracy)
        
    classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
    accknn.append(Accuracy)
        
    classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
    accnav.append(Accuracy)
        
    classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
    accdes.append(Accuracy)
        
    classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
    accrf.append(Accuracy)
    
result=selectk_Classification(pcalist,acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

ValueError: Found input variables with inconsistent numbers of samples: [2, 399]

In [76]:
result

               Logistic  SVMl SVMnl   KNN Navie Decision Random
PCA Components
pcalist            0.64  0.64  0.65  0.65  0.64     0.74   0.73